"""add log_entry table

Revision ID: 56f9a522c3df
Revises: 4e5b36887e8a
Create Date: 2026-02-16 14:44:31.366289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56f9a522c3df'
down_revision: Union[str, None] = '4e5b36887e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('logger_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('exception', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    # ### end Alembic commands ###
